config/routes.rb
Rails.application.routes.draw do
  root to: 'trucks#index'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  get '/trucks', to: 'trucks#index'

  resources :users

  resources :trucks do
    resources :menus
  end

  resources :trucks do
    resources :locations
  end

end

app/models/truck.rb
class Truck < ApplicationRecord
  validates :truck_name, presence: true
  belongs_to :user
  has_many :menus
  has_many :locations

  has_attached_file :truck_image,
                    styles: { :large => "600x400>",
                              :medium => "300x200>",
                              :small => "100x75>",
                              :thumb => "60x42>" },
                    :default_url => "/assets/avatar.png"

  validates_attachment_content_type :truck_image, content_type: /\Aimage\/.*\z/
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController

  before_action :find_user

  def index
    @trucks = Truck.all
  end

  def new
    @truck = Truck.new
  end

  def create
    @truck = Truck.create(truck_params)
    if current_user == nil
      flash[:error] = @truck.errors.full_messages.join(", ")
      redirect_to new_user_session_path
      return
    else @truck.user_id = current_user.id
    end
    if @truck.save
      flash[:notice] = "Successfully created truck"
      redirect_to user_path(@truck.user_id)
    else
      flash[:error] = @truck.errors.full_messages.join(", ")
      redirect_to new_truck_path
    end
  end

  def show
    @truck = Truck.find_by_id(params[:id])
    @locations = @truck.locations
  end


  def edit
    @truck = Truck.find_by_id(params[:id])
  end

  def update
    @truck = Truck.find(params[:id])
    if @truck.update(truck_params)
      flash[:notice] = "Successfully updated truck."
      redirect_to user_path(@truck.user_id)
    else
      flash[:error] = @truck.errors.full_messages.join(", ")
      redirect_to edit_trucks_path
    end
  end

  def destroy
    @truck = Truck.find(params[:id])
    @truck.destroy
    flash[:notice] = "Successfully deleted truck."
    redirect_to user_path(@truck.user_id)
  end

  private

  def find_user
    @user = User.find_by_id(params[:user_id])
  end

  def truck_params
    params.require(:truck).permit(:truck_name, :phone_number, :address, :is_cash_only, :picture, :info, :category, :general_hours)
  end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/edit.html.erb
<div class="col-xs-2"></div>
<div class="col-xs-8">

<%= form_for @truck, :html => { multipart: true, :class => "form-horizontal"} do |f| %>
  <div class="col-sm-8">
    <%= f.text_field :truck_name, placeholder: "Truck Name", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.text_field :phone_number, placeholder: "Phone Number", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.text_area :info, placeholder: "Food Truck info", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.text_field :category, placeholder: "category", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    Is Cash Only? <%= f.check_box :is_cash_only, {}, "true" %>
  </div>
  <div class="col-sm-8">
    <p>
      Paste a link or upload a photo of your truck
    </p>
    <%= f.text_field :picture, placeholder: "Image", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.file_field :avatar %>
  </div>
  <div class="col-sm-8">  
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
<div class="col-xs-2"></div>

app/views/trucks/index.html.erb
<div class="welcome_page">
  <div class="welcome-top">
    <h1>Welcome</h1>
    <h3>Trucking Good Food</h3>

    <p>
      This website helps you find food trucks near you. Please <%= link_to "download", "https://appsto.re/us/VYXIjb.i" %> our iOS app to use on an iphone. If you are a food truck owner and wish to add your truck please create an account and add your truck to the our website.
    </p>
    <p>
      Below is a list of food trucks
    </p>

  </div>

  <div class='container index_truck_container'>
    <div class='row index_truck_list'>

      <% @trucks.each do |truck| %>
      <div class='index_truck_card col-xs-4'>
        <div class="test">
          <div class="row">
          <div class="col-xs-4"></div>
        <div class="index_truck_picture col-xs-4">
          <%= image_tag truck.picture unless truck.picture.blank? %>
        </div>
        <div class="col-xs-4"></div>
        </div>
        <strong><%= truck.user.business_name%></strong>
        <br>
        <strong id="index_truck_name"><%= truck.truck_name %></strong>
        <br>
        <%= link_to 'More Info', truck_path(truck.id), class: "index_truck_more"%>
        <br>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trucks/new.html.erb
<div class="col-xs-2"></div>
<div class="col-xs-8">

<%= form_for @truck, :html => { multipart: true, :class => "form-horizontal"} do |f| %>
  <div class="col-sm-8">
    <%= f.text_field :truck_name, placeholder: "Truck Name", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.text_field :phone_number, placeholder: "Phone Number", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.text_area :info, placeholder: "Food Truck info", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.text_field :category, placeholder: "category", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    Is Cash Only? <%= f.check_box :is_cash_only, {}, "true" %>
  </div>
  <div class="col-sm-8">
    <p>
      Paste a link or upload a photo of your truck
    </p>
    <%= f.text_field :picture, placeholder: "Image", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.file_field :avatar %>
  </div>
  <div class="col-sm-8">
    <%= f.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
<div class="col-xs-2"></div>

app/views/trucks/show.html.erb
<div class="one_truck_container container">
   <div class="row">

  <div class="col-xs-6 truck_show_info">
    <div id="truck_info">
      <%= image_tag @truck.truck_image.url(:medium) %>
      <br>
      Name:
      <%= @truck.truck_name %>
      <br>
      Phone Number:
      <%= @truck.phone_number %>
      <br>
      Description:
      <%= @truck.info %>
      <br>
      Category:
      <%= @truck.category %>
      <br>
      <%= link_to 'Edit this truck', edit_truck_path(@truck), class: "btn btn-primary" %>
    </div>

  </div>
  <div class="col-xs-6 truck_show_location">
    <% @locations.each do |location| %>
    <div>
      <span><strong>Address: </strong><%= location.address %></span>
    </div>
    <div>
      <span><strong>Hours: </strong><%= location.hours %></span>
    </div>
    <div>
      <%= link_to "Edit location", edit_truck_location_path(@truck.id, location.id), class: "btn btn-primary location_btn" %>
      <%= link_to "Delete", truck_location_path(@truck.id, location.id), method: :delete, :class => "btn btn-danger", data: { confirm: "Are you sure you want to delete this location?"} %>
    </div>
    <br>
    <% end %>
    <br>
    <%= link_to "Add a location for this truck", new_truck_location_path(@truck), class: "btn btn-primary" %>
  </div>
</div>
<%= link_to 'Menu', truck_menus_path(@truck) %>
</div>