config/routes.rb
Rails.application.routes.draw do
  root to: 'trucks#index'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  get '/trucks', to: 'trucks#index'

  resources :users

  resources :trucks do
    resources :menus
  end

  resources :trucks do
    resources :locations
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :business_name, :permit_id, presence: true
  validates :password, :password_confirmation, presence: true, :on => :create
  validates :permit_id, :email, uniqueness: true
  validates :password, confirmation: true

  has_secure_password
  has_many :trucks
  has_many :menus, through: :trucks
  has_many :locations, through: :trucks


  has_attached_file :avatar,
                    styles: { :large => "600x400>",
                              :medium => "300x200>",
                              :small => "100x75>",
                              :thumb => "60x42>" },
                    :default_url => "/assets/avatar.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :skip_password_attribute, only: :update

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = "Successfully Signed-in"
      login(@user)
      redirect_to @user
    else
      flash[:error] = @user.errors.messages
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @trucks = @user.trucks
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Successfully updated profile!!"
      redirect_to user_path(params[:id])
    else
      flash[:error] = @user.errors
      redirect_to edit_user_path
      #check this redirect_to
    end
  end

  private

  def skip_password_attribute
    if params[:password].blank? && params[:password_confirmation].blank?
      params.except!(:password, :password_confirmation)
    end
  end

  def user_params
    params.require(:user).permit(:business_name, :email, :password, :logo, :permit_id, :avatar, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="col-xs-2"></div>
<div class="col-xs-8">

  <%= form_for @user, :html => { multipart: true, :class => "form-horizontal center"} do |f| %>

  <div class="col-md-8">
    <%= f.text_field :business_name, placeholder: "Business Name", class: "form-control" %>
  </div>

  <div class="col-md-8">
    <%= f.text_field :permit_id, placeholder: "Permit ID", class: "form-control" %>
  </div>

  <div class="col-md-8">
    <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <h4>
      Paste a link for your logo or upload a file</h4>
    <%= f.text_field :logo, placeholder: "Logo", class: "form-control" %>
  </div>

  <div class="col-md-8">
    <%= f.file_field :avatar %>
  </div>

  <div class="col-md-8">
    <%= f.submit "Update", class: "btn btn-default btn-primary" %>
  </div>
  <% end %>
</div>
<div class="col-xs-2"></div>

app/views/users/index.html.erb
<h1>Welcome to the Food Truck App</h1>

<div>
  There are currently <%= @users.length %> users signed up!
</div>

app/views/users/new.html.erb
<div class="col-xs-2"></div>
<div class="col-xs-8">

  <%= form_for @user, :html => { multipart: true, :class => "form-horizontal center"} do |f| %>

  <div class="col-sm-8">
    <%= f.text_field :business_name, placeholder: "Business Name", class: "form-control" %>
  </div>

  <div class="col-sm-8">
    <%= f.text_field :permit_id, placeholder: "Permit ID", class: "form-control" %>
  </div>

  <div class="col-sm-8">
    <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
  </div>

  <div class="col-sm-8">
    <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
  </div>

  <div class="col-sm-8">
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <h4>
      Paste a link for your logo or upload a photo</h4>
      <%= f.text_field :logo, placeholder: "Logo", class: "form-control" %>
    </div>

    <div class="col-sm-8">
      <%= f.file_field :avatar %>
    </div>

  <div class="col-sm-8">
    <%= f.submit "Sign Up", class: "btn btn-default btn-primary" %>
  </div>
  <% end %>
</div>
<div class="col-xs-2"></div>

app/views/users/show.html.erb
<div class="col-xs-6 user_show">
  <%= image_tag @user.logo unless @user.logo.blank? %>
  <%= image_tag @user.avatar.url(:medium), class: "user_show_avatar" %>
  <br>
  Welcome:
  <strong><%= @user.business_name %></strong>
  <br>
  Email:
  <%= @user.email %>
  <br>
  Permit ID:
  <%= @user.permit_id %>
  <br>
  <br>
  <%= link_to "Edit Your Profile", edit_user_path(@user) %>
  <br>
  <br>
</div>
<div class="col-xs-6 user_truck">

  <% @trucks.each do |truck| %>
  <div class="user_truck_card">
    <div>
      <%= image_tag truck.picture, :class => "user_truck_image" unless truck.picture.blank? %>
    </div>
    <span><%= truck.truck_name %></span>
    <br>
    <%= link_to "More Info", truck_path(truck.id) %>
    <br>
    <%= link_to "Edit", edit_truck_path(truck.id), {:class => "btn btn-primary"} %>
    <%= link_to "Delete", truck, method: :delete, :class => "btn btn-danger", data: { confirm: "Are you sure you want to delete this truck?"} %>
    <br>
  </div>
  <% end %>
  <%= link_to 'Add a new Truck', new_truck_path, class: "btn btn-primary" %>
</div>