config/routes.rb
Rails.application.routes.draw do
  root to: 'trucks#index'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  get '/trucks', to: 'trucks#index'

  resources :users

  resources :trucks do
    resources :menus
  end

  resources :trucks do
    resources :locations
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Trucking Good Food</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', href="https://fonts.googleapis.com/css?family=Athiti|Varela+Round|Work+Sans", media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/trucks">Trucking Good Food</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
        <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to "Create Account", new_user_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |name, msg| %>
  <p>
    <small>
      <%= name.capitalize %>:
      <%= msg %>
    </small>
  </p>
  <% end %>

  <%= yield %>
</body>
</html>